// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMcD9VrxeWSSWgAQ6gmalL5K6Da-jjoeY',
    appId: '1:532448756108:web:79d9b0bac037cf850596a9',
    messagingSenderId: '532448756108',
    projectId: 'quizwhiz-c27c2',
    authDomain: 'quizwhiz-c27c2.firebaseapp.com',
    storageBucket: 'quizwhiz-c27c2.firebasestorage.app',
    measurementId: 'G-8L0Q240S2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_gXOsSWoUxZxb4KR1e42Gba0skpvrK9o',
    appId: '1:532448756108:android:fc8e93e720b427070596a9',
    messagingSenderId: '532448756108',
    projectId: 'quizwhiz-c27c2',
    storageBucket: 'quizwhiz-c27c2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzR8vP4odEi_3CiqCURC3HTw8zVfD9ax8',
    appId: '1:532448756108:ios:e6268311bece832b0596a9',
    messagingSenderId: '532448756108',
    projectId: 'quizwhiz-c27c2',
    storageBucket: 'quizwhiz-c27c2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzR8vP4odEi_3CiqCURC3HTw8zVfD9ax8',
    appId: '1:532448756108:ios:e6268311bece832b0596a9',
    messagingSenderId: '532448756108',
    projectId: 'quizwhiz-c27c2',
    storageBucket: 'quizwhiz-c27c2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMcD9VrxeWSSWgAQ6gmalL5K6Da-jjoeY',
    appId: '1:532448756108:web:540e554c77e6d2de0596a9',
    messagingSenderId: '532448756108',
    projectId: 'quizwhiz-c27c2',
    authDomain: 'quizwhiz-c27c2.firebaseapp.com',
    storageBucket: 'quizwhiz-c27c2.firebasestorage.app',
    measurementId: 'G-LGD0L0ESRB',
  );
}
